[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040"
# To run directly on a connected pico without a probe
# runner = "elf2uf2-rs -d"

[build]
# Cortex-M0 and Cortex-M0+
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
