[package]
name = "mqtt"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = { workspace = true, optional = true }
serde = { version = "1.0.219", features = ["derive"], optional = true }
[features]
defmt = ["dep:defmt"]
serde = ["dep:serde"]
